# See https://github.com/gohugoio/hugoThemes#themetoml for an example
name = "Hillbilly"
license = "MIT"
licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE"
description = ""
homepage = "https://rockinghat.com/"
tags = []
features = []
min_version = "0.115.4"

[author]
  name = "Heath Robertson"
  homepage = "RockingHat.com"
